### ISSUE TITLE
tp_to_adm() throws an error if the parameter h is given a function argument

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/admtools#43]
https://github.com/MindTheGap-ERC/admtools/blob/3d9da822d9c9163721cb5fdb41682e123e01a33b/R/tp_to_adm.R#L37

reprex:
```
h1 = c(610, 649, 696, 766, 829, 893, 962, 1027, 1079, 1152, 1199, 1246, 1298, 1347, 1402)
age = seq(from = 0, by = 100, along.with = h1)

t_tp <- tp_time_det(age)
h_tp = tp_height_det(heights = h1)

Kowala_Famennian <- tp_to_adm(t = t_tp,
                              h = h_tp, 
                              T_unit = T_unit, 
                              L_unit = L_unit)
```
gives `Error in duplicated.default(h) : duplicated() applies only to vectors`

It is resolved if `h_tp = tp_height_det(heights = h1)` is skipped but the logic of the documentation leads you to use that

**Comment by NiklasHohmann** [comment]
@EmiliaJarochowska per the documentation,
1. `tp_to_adm` expects vectors as inputs for `t` and `h`
2. `tp_height_det`  and `tp_time_det` return functions for usage with `strat_cont_to_multiadm` and `sedrate_to_multiadm`

Pass `h1` and `age` directly to `tp_to_adm`
